name = input("What is your name? ")
age = input("How old are you? ")
hobby = input("What is your favorite hobby? ")
favorite_dish = input("What is your favorite dish?")
sport = input("What is your favourite sport?")
city = input("Which city are you from? ")
country = input("Which Country are you from? ")

print("\n Welcome", name + "!")
print(f"You are {age} years old.")
print(f"You love {hobby}.")
print(f"You love eating {favorite_dish}")
print(f"You love playing {sport}")
print(f"You are from {city}.")
print(f"You are from {country}.")
print("Nice to meet you!")
